artifacts_dir: artifacts
batch_size: 128
cache_dir: artifacts/cache
context_length: 160
d_model: 160
device: auto
dropout: 0.15
epochs: 18
evaluation_csv: artifacts/evaluation.csv
grad_accum_steps: 2
kronos_repo: NeoQuasar/Kronos-base
kronos_tokenizer_repo: NeoQuasar/Kronos-Tokenizer-base
lambda_dir: 0.25
learning_rate: 0.0003
model_path: artifacts/kronos_p100.pth
n_heads: 5
n_layers: 3
per_ticker_scaler: true
predictions_path: artifacts/predictions.json
random_seed: 123
scaler_path: artifacts/scalers.pkl
targets:
- Open
- Close
- Low
- High
- Volume
ticker_list:
- NVDA
- AMD
- INTC
- TXN
- MCHP
- QCOM
- MSFT
- ORCL
- NOW
- CSCO
- IBM
- INTU
- SMCI
- AAPL
- AMZN
- TSLA
- GOOGL
- META
- PYPL
- GPN
- CWEN
- FSLR
- SEDG
- BE
- MNTK
- AMTX
- CLNE
- CEG
- BN
- NEE
- COP
- DVN
- ENB
- XOM
- PSX
- SHEL
- MPC
- ED
- PPL
- SO
train_end_date: '2025-05-30'
train_start_date: '2018-01-01'
use_indicators: true
use_kronos_base: false
valid_end_date: '2025-08-22'
valid_start_date: '2025-06-01'
weight_decay: 0.0001
